version: '3.7'

services:
  microservice1:
    build: ./microservice1
    volumes:
      - ./microservice1:/app
    ports:
      - "3000:3000"

  microservice2:
    build: ./microservice2
    volumes:
      - ./microservice2:/app
    ports:
      - "3001:3001"

  sonarqube:
    image: sonarqube:lts
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=sonarqube
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql/data
    expose:
      - "5432"

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
