name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        ports:
          - 2376:2376
        env:
          DOCKER_HOST: tcp://localhost:2376
          DOCKER_TLS_VERIFY: 1
          DOCKER_TLS_CERTDIR: /certs
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /tmp/docker-certs:/certs/client

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker image for Microservice 1
        uses: docker/build-push-action@v2
        with:
          context: ./microservice1
          file: ./microservice1/Dockerfile
          push: true
          tags: cyas94/microservice1:latest

      - name: Build and Push Docker image for Microservice 2
        uses: docker/build-push-action@v2
        with:
          context: ./microservice2
          file: ./microservice2/Dockerfile
          push: true
          tags: cyas94/microservice2:latest

      - name: Run Unit Tests for Microservice 1
        run: |
          cd microservice1
          npm install
          npm test

      - name: Run Unit Tests for Microservice 2
        run: |
          cd microservice2
          npm install
          npm test
